server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
